CREATE DATABASE SmartFarm;
CREATE USER 'SmartFarmApp'@'localhost' IDENTIFIED BY 'SmartFarm2020';
GRANT ALL ON SmartFarm.* TO 'SmartFarmApp'@'localhost';

USE SmartFarm;
INSERT INTO usuario VALUES (1, "Prueba", "admin@gmail.com", "2020/05/12", "Usuario", "123", "Admin");

INSERT INTO TipoAnimal VALUES(1, "CAPRINO");
INSERT INTO TipoAnimal VALUES(2, "EQUINO");
INSERT INTO TipoAnimal VALUES(3, "OVINO");
INSERT INTO TipoAnimal VALUES(4, "PORCINO");
INSERT INTO TipoAnimal VALUES(5, "VACUNO");

-- CAPRINOS
INSERT INTO Raza VALUES(1, "ANGLO NUBIAN", 1);
INSERT INTO Raza VALUES(2, "BOER", 1);
INSERT INTO Raza VALUES(3, "CRIOLLA", 1);
INSERT INTO Raza VALUES(4, "PARDO ALPINA", 1);
-- EQUINOS
INSERT INTO Raza VALUES(5, "ANGLO ÁRABE", 2);
INSERT INTO Raza VALUES(6, "ÁRABE", 2);
INSERT INTO Raza VALUES(7, "CRIOLLO", 2);
INSERT INTO Raza VALUES(8, "CUARTO DE MILLA", 2);
-- OVINOS
INSERT INTO Raza VALUES(9, "ARGENTINO", 3);
INSERT INTO Raza VALUES(10, "CORRIEDALE", 3);
INSERT INTO Raza VALUES(11, "LINCOLN", 3);
INSERT INTO Raza VALUES(12, "MERINO", 3);
-- PORCINOS
INSERT INTO Raza VALUES(13, "DUROC", 4);
INSERT INTO Raza VALUES(14, "HAMPSHIRE", 4);
INSERT INTO Raza VALUES(15, "LANDRACE", 4);
INSERT INTO Raza VALUES(16, "YORKSHIRE", 4);
-- VACUNOS
INSERT INTO Raza VALUES(17, "CHIANINA", 5);
INSERT INTO Raza VALUES(18, "HOLANDO ARGENTINO", 5);
INSERT INTO Raza VALUES(19, "LIMOUSIN", 5);
INSERT INTO Raza VALUES(20, "VACA CANARIA", 5);

INSERT INTO Genero VALUES(1, "HEMBRA");
INSERT INTO Genero VALUES(2, "MACHO");
